### ISSUE TITLE
validate new stack does not conflict with existing stack

### ISSUE THREAD

**Issue by zaro0508** [Sage-Bionetworks-IT/pre-commit-provisioner#2]
If a new CFN stack is deployed with the same name as an existing stack, AWS CFN will try to replace the existing stack with the new stack definition.  This may cause the existing stack to get into a bad state which is not good.  We need a linter to check that a new or updated `stack_name` isn't named the same as an existing stack that's already been deployed to AWS. 

Examples 1:
1. Assume `foo` stack is already deployed to AWS
2. New commit foo.yaml file containing stack_name: "bar"
Result: compare-stack-and-file-names linter should cause this case to fail

Examples 2:
1. Assume `foo` stack is already deployed to AWS
2. New commit foo.yaml file containing stack_name: "foo"
Result: Fail with message "Foo stack already deployed to Cloudformation"

Examples 3:
1. Assume `foo` stack is already deployed to AWS
2. New commit bar.yaml reanmed to foo.yaml file containing stack_name: "foo"
Result: Fail with message "Foo stack already deployed to Cloudformation"

**Comment by zaro0508** [comment]
I realized that this is not possible because cloudformation is designed to be able to update stacks with the same name.  I think example 1 is the best we can do.

**Comment by cascadianblue** [comment]
So, if I understand correctly, we have already implemented this, right (just handling example 1)?

**Comment by zaro0508** [comment]
yes. we've got example 1 covered, example 2 & 3 goes against the design of CFN & Sceptre.  Nothing more to do so closing this issue
