### ISSUE TITLE
Validate all Sceptre parameter values are quoted

### ISSUE THREAD

**Issue by zaro0508** [Sage-Bionetworks-IT/pre-commit-provisioner#4]
Sceptre allows passing non-string values like int or booleans however Cloudformation only supports string types.  This means every parameter value in a sceptre templates needs to be in quotes otherwise it will fail when it gets handed off to cloudformation.  We need a validator that checks that all sceptre parameter values are in quotes.  Maybe also have an option to automatically quote all values as well.

The pre-commit [double-quote-string-fixer](https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/string_fixer.py) hook is a good starting point for this linter.

**Comment by cascadianblue** [comment]
We decided to just use yamllint, so I'm closing this issue
